#!/usr/bin/env bash
# =============================================================================
# scripts/provision_full_test_env.sh
# =============================================================================
# Provisions every prerequisite the test suite needs, so that
# `unittest discover` reports PASS/FAIL for all tests and SKIPS NOTHING.
#
# Without this, a fresh clone skips 11 tests because:
#   - build/environments/env_<env>.sql are gitignored (only *.example.sql ship)
#   - build/config.local.env is gitignored (written by setup.sh)
#   - the te_mgmt_* databases have not been deployed
#
# Usage:
#   bash scripts/provision_full_test_env.sh
#   python3 -m unittest discover -s tests -p "test*.py"
#
# Requires: psql on PATH, a reachable PostgreSQL server, PGUSER/PGHOST/PGPORT
# set (or the libpq defaults).
#
# Note on passwords: the generated env_<env>.sql keep the literal
# '__INJECT_AT_DEPLOY__' placeholder from the template. It is a valid role
# password for a local test instance and keeps
# tests/test_security.py::test_env_sql_files_no_hardcoded_passwords green.
# Never use these files against a real environment.
# =============================================================================

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD="${ROOT}/build"
ENVS=(dev test staging prod)

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
ok()   { echo -e "${GREEN}[✓]${NC} $*"; }
info() { echo -e "${YELLOW}[»]${NC} $*"; }
die()  { echo -e "${RED}[✗]${NC} $*"; exit 1; }

command -v psql >/dev/null 2>&1 || die "psql not on PATH — install the PostgreSQL client."
psql -tAc 'SELECT 1' >/dev/null 2>&1 || die "Cannot reach PostgreSQL. Set PGUSER/PGHOST/PGPORT and start the server."
ok "PostgreSQL reachable"

# ── 1. Concrete env launchers from the committed templates ──────────────────
for env in "${ENVS[@]}"; do
    src="${BUILD}/environments/env_${env}.example.sql"
    dst="${BUILD}/environments/env_${env}.sql"
    [[ -f "$src" ]] || die "Missing template: $src"
    cp "$src" "$dst"
    ok "env_${env}.sql created from template"
done

# ── 2. config.local.env in the format setup.sh emits ────────────────────────
# NOTE: build/config.env.example is NOT a config.local.env template — it holds
# setup.sh's input defaults and uses different variable names (DEV_DB_NAME vs
# PG_DB_DEV). The loaders read the PG_*_<ENV> names below.
if [[ ! -f "${BUILD}/config.local.env" ]]; then
    cat > "${BUILD}/config.local.env" <<EOF
# Generated by scripts/provision_full_test_env.sh for local testing only.
DB_ENGINE=postgresql
TARGET_ENV=dev

PG_HOST=${PGHOST:-localhost}
PG_PORT=${PGPORT:-5432}
PG_SUPERUSER=${PGUSER:-postgres}
PG_SUPERUSER_PASSWORD=${PGPASSWORD:-}
PG_DB_DEV=te_mgmt_dev
PG_DB_TEST=te_mgmt_test
PG_DB_STAGING=te_mgmt_staging
PG_DB_PROD=te_mgmt_prod
PG_SCHEMA_DEV=te_dev
PG_SCHEMA_TEST=te_test
PG_SCHEMA_STAGING=te_staging
PG_SCHEMA_PROD=te_prod
PG_APP_USER_DEV=te_dev_user
PG_APP_USER_TEST=te_test_user
PG_APP_USER_STAGING=te_stg_user
PG_APP_USER_PROD=te_prod_user
PG_APP_PASSWORD_DEV=__INJECT_AT_DEPLOY__
PG_APP_PASSWORD_TEST=__INJECT_AT_DEPLOY__
PG_APP_PASSWORD_STAGING=__INJECT_AT_DEPLOY__
PG_APP_PASSWORD_PROD=__INJECT_AT_DEPLOY__
PG_CONN_LIMIT_DEV=10
PG_CONN_LIMIT_TEST=15
PG_CONN_LIMIT_STAGING=25
PG_CONN_LIMIT_PROD=50
EOF
    ok "config.local.env generated (PG_*_<ENV> names the loaders expect)"
else
    info "config.local.env already present — leaving as is"
fi

# ── 3. Deploy every environment ─────────────────────────────────────────────
for env in "${ENVS[@]}"; do
    info "Deploying ${env}…"
    bash "${BUILD}/deploy_all.sh" "$env" >/dev/null 2>&1 \
        || die "Deployment failed for ${env}. Re-run: bash build/deploy_all.sh ${env}"
    ok "${env} deployed"
done

echo
ok "All prerequisites provisioned. The suite should now skip nothing:"
echo "    python3 -m unittest discover -s tests -p \"test*.py\""
